services:
  ambev.developerevaluation.database:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - database_data:/var/lib/postgresql/data
  
  ambev.developerevaluation.messaging:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - messaging_data:/var/lib/rabbitmq

volumes:
  database_data:
  messaging_data: